name: Continuous Integration
on: 
  push:
    paths-ignore:
      - "README.md"
      - ".gitignore"
  pull_request:
    paths-ignore:
      - "README.md"
      - ".gitignore"
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build --target test --tag my-test-image .
      - run: docker run --env-file .env.test my-test-image:latest
